---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# vjsim

<!-- badges: start -->
<!-- badges: end -->

The goal of `vjsim` is to simulate a simple vertical jump model to provide an educational tool for helping in understanding elementary biomechanical concepts and jump profiles used in sport science.

## Installation

You can install the development version from [GitHub](https://github.com/mladenjovanovic/vjsim) with:

``` r
# install.packages("devtools")
devtools::install_github("mladenjovanovic/vjsim")
```

## Usage

Please read accompanying vignettes for examples and usage of the `vjsim` package


1. [Introduction to vjsim](https://htmlpreview.github.io/?https://github.com/mladenjovanovic/vjsim/master/doc/introduction-vjsim.html)

This vignette discusses the basic mechanical representation of the vertical jump system. Please read this to understand the overall setup. Access it by clicking the above link or running the following code:

``` r
vignette("introduction-vjsim")
```

2. [Simulation in vjsim](https://htmlpreview.github.io/?https://github.com/mladenjovanovic/vjsim/master/doc/simulation-vjsim.html)

This vignette continues the [Introduction to vjsim](https://htmlpreview.github.io/?https://github.com/mladenjovanovic/vjsim/master/doc/introduction-vjsim.html) vignette and expands on the topic of simulation and how vertical jump is simulated. Access it by clicking the above link or running the following code:

``` r
vignette("simulation-vjsim")
```

3. [Profiling in vjsim](https://htmlpreview.github.io/?https://github.com/mladenjovanovic/vjsim/master/doc/profiling-vjsim.html)

Once you understand how the [Simulation in vjsim](https://htmlpreview.github.io/?https://github.com/mladenjovanovic/vjsim/master/doc/simulation-vjsim.html) works, we can start playing with profiling. Force-Velocity (FV), Load-Velocity (LV), and other profiles are discussed, as well as the idea of "optimal" FV profile. Access it by clicking the above link or running the following code:

``` r
vignette("profiling-vjsim")
```

4. [Exploring vjsim](https://htmlpreview.github.io/?https://github.com/mladenjovanovic/vjsim/master/doc/exploring-vjsim.html)

In this vignette we are going to explore various assumptions of the model, "optimal" FV profiles and some other interesting questions. Access it by clicking the above link or running the following code:

``` r
vignette("exploring-vjsim")
```

## Shiny App

(Video and App will be added)
